# prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "triton"
    scrape_interval: 5s
    static_configs:
      - targets: ["triton:8002"]
    metrics_path: /metrics

  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9090"]
